# Constants
APPNAME = "TangemLite"


lane :buildAppStore do |options|
  increment_version_number(
  	version_number: options[:versionName]
  )

  increment_build_number(
    build_number: options[:versionCode]
  )


  build_app(
    xcargs: "-allowProvisioningUpdates",
    output_name: APPNAME + "-release",
    scheme: "Tangem Tap",
    export_method: "app-store",
    clean: true,
    silent: true,
    configuration: "Release"
  )

end

lane :buildAdHoc do |options|

  increment_version_number(
  	version_number: options[:versionName]
  )

  increment_build_number(
    build_number: options[:versionCode]
  )

  build_app(
    xcargs: "-allowProvisioningUpdates",
    output_name: APPNAME + "-adhoc",
    scheme: "Tangem beta",
    export_method: "ad-hoc",
    clean: true,
    silent: true,
    configuration: "Release"
  )

end

lane :test do
run_tests(
  workspace: "Tangem Tap.xcworkspace",
  scheme: "Tangem Tap",
  clean: true
)
end

lane :refresh_dsyms do |options|
  download_dsyms(version: options[:version], build_number: options[:build_number]) 
  upload_symbols_to_crashlytics 
  clean_build_artifacts
end

